### ISSUE TITLE
AddBinaryString doesn't work at all

### ISSUE THREAD

**Issue by JeremieMelo** [mineshmathew/pyTorch_RNN_Examples#2]
Download your code, run in jupyter notebook, you forget to change y from map object to list
and the loss never reduces
Cannot get the result shown in your notebook. Didn't see any convergence.

**Comment by mineshmathew** [comment]
Hey,

It took me sometime to figure out what you are saying. It is a good practice always to add the error so that others can make better sense of what  you are saying

The notebook for binary addition is a Python2 notebook and there it works fine. The issue is when it is run using python3. The exact problem is with the line 
`y=np.array(map(int, num3Binary[::-1]))`
Like it is mentioned in the comment it is taken from the post - https://stackoverflow.com/questions/29091869/convert-bitstring-string-of-1-and-0s-to-numpy-array
In python3.x this behaves differently and returns a map object instead of an np array. Thats why it threw an error. The same is mentioned in the above stack-overflow thread
